name: Build Android APK (FINAL DEBUG)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        
    - name: Set up Android SDK and Accept Licenses
      uses: android-actions/setup-android@v3
      with:
        packages: "platforms;android-32 build-tools;32.0.0"
        accept-android-sdk-licenses: true

    - name: Install, Build, and List Files
      run: |
        echo "--- Installing Cordova..."
        npm install -g cordova
        
        echo "--- Creating Project..."
        cordova create temp_build
        cd temp_build
        cp -r ../www/* www/
        cp ../config.xml .

        echo "--- Adding Android Platform..."
        cordova platform add android@11
        
        echo "--- Attempting The Build..."
        # We add '|| true' so the workflow continues to the next command even if this fails
        cordova build android --release -- --minSdkVersion 22 || true
        
        echo "--- LISTING ALL FILES CREATED IN THE PROJECT ---"
        # This will show us exactly what was created, and where. This is the most important part.
        ls -R ..
