name: Build Android APK (DEBUGGING)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        
    - name: Set up Android SDK and Accept Licenses
      uses: android-actions/setup-android@v3
      with:
        packages: "platforms;android-32 build-tools;32.0.0"
        accept-android-sdk-licenses: true

    - name: Install, Build, and Debug
      run: |
        echo "--- STEP 1: Installing Cordova ---"
        npm install -g cordova
        
        echo "--- STEP 2: Creating Cordova Project ---"
        cordova create temp_build
        cd temp_build
        cp -r ../www/* www/
        cp ../config.xml .

        echo "--- STEP 3: Adding Android Platform ---"
        cordova platform add android@11
        
        echo "--- STEP 4: Attempting The Build (The important part) ---"
        # The '|| true' at the end forces the script to continue even if the build fails
        cordova build android --release -- --minSdkVersion 22 || true
        
        echo "--- STEP 5: Listing All Files In The Project ---"
        # This will show us exactly what was created, and where
        ls -R ..
